### PR TITLE
A simpler, more elegant solution than using regexes

### PR DESCRIPTION
**Pull request by Data-Meister**
Added benefit of not worrying about regex escaping.

### CODE REVIEW

**Comment by Data-Meister** [comment]
P.S. I've got some similar code for doing a substring replace

newString = originalStr.split subStr .join replacementStr

I could PR this in the same place. Or would it go better in another chapter?

**Comment by lolmaus** [comment]
And this is also faster: http://jsperf.com/occurrences-of-substring

But your commit is wrong.

```coffee
message.split " a " .length - 1
```

would compile to

```js
message.split(" a ".length - 1);
```

while we want

```js
message.split(" a ").length - 1;
```

Thus, you want either of these:

```coffee
message.split(" a ").length - 1

message
  .split " a "
  .length - 1
```

**Comment by Data-Meister** [comment]
Cheers! I'll redo the PR with that corrected. 

Shall I include the string replace code?

**Comment by lolmaus** [comment]
> Shall I include the string replace code?

Wouldn't hurt! But check of there a better section to place it into.

**Comment by sukima** [comment]
Why did this close? A pull request can be appended and modified by rebaseing and force pushing to the original branch.

This is a down side to using GitHub web interface over the Git command line tool.

**Comment by Data-Meister** [comment]
Oh right, thanks for the tip sukima. I closed it with the intention of reverting then re committing. Will do this tonight hopefully.

**Pull request closed without merging**
