### PR TITLE
Fixed a typo

### PR DESCRIPTION
**Pull request by dotJoel**
This sentence about "natural grammar" had a spelling mistake that I could not let go.
It is obviously talking about the verb "send", and the word "very" was a typo.

### CODE REVIEW

**Comment by michaelglass** [comment]
while you're at it: "particle _to_" should also be "preposition _to_".

**Comment by michaelglass** [comment]
fwiw:
commit messages should be informative & imperative.

"fix typo" is better
"fix typo in copy" is even better

**Comment by sukima** [comment]
FWIW: http://chris.beams.io/posts/git-commit/

**Comment by lolmaus** [comment]
Do we demand this to be squashed into one commit? I don't feel like it's necessary. +1 to merge.

**Pull request merged**
